# Generated by Django 4.2 on 2023-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_alter_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
