# Generated by Django 4.2 on 2023-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_alter_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='redirect_url',
            field=models.CharField(default='https://google.com', max_length=255),
        ),
    ]
