# Generated by Django 4.2 on 2023-04-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0011_click_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='device',
            field=models.CharField(max_length=255),
        ),
    ]
